sudo: false
language: ruby
rvm:
  - 2.5.3
before_install: gem install bundler -v 1.17.1
notifications: false

env:
  global:
    - CC_TEST_REPORTER_ID=a3447ea2adb73c8f2f39fec720291342b44a8e8b72aca541d59476b9ea0c0db4

before_script:
  - bundle exec rspec && CODECLIMATE_REPO_TOKEN=a3447ea2adb73c8f2f39fec720291342b44a8e8b72aca541d59476b9ea0c0db4
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

scripts:
  - bundle exec rspec spec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT